# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_user',
        ),
        migrations.AlterField(
            model_name='account',
            name='host',
            field=models.ManyToManyField(blank=True, null=True, to='audit.HostUserBind'),
        ),
        migrations.AlterField(
            model_name='account',
            name='host_group',
            field=models.ManyToManyField(blank=True, null=True, to='audit.HostGroup'),
        ),
    ]
